export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';


export const LOGIN_STATUS_SET = 'LOGIN_STATUS_SET';
export const LOGIN_ATTEMPT_BEGIN = 'LOGIN_ATTEMPT_BEGIN';
export const LOGIN_ATTEMPT_END_SUCCESS = 'LOGIN_ATTEMPT_END_SUCCESS';
export const LOGIN_ATTEMPT_END_FAILED = 'LOGIN_ATTEMPT_END_FAILED';
export const LOGIN_ABANDON = 'LOGIN_ABANDON';


export const SYNC_RESPONSE_AVAILABLE = 'SYNC_RESPONSE_AVAILABLE';
export const FURSUIT_BADGES_RESPONSE_AVAILABLE = 'FURSUIT_BADGES_RESPONSE_AVAILABLE';